export const sampleData = [
  {
    id: 1,
    name: "영근",
    pharmacy_name: "졸리다",
    address: "서울특별시 금천구 영근로",
    lat: 37.5173319258532,
    lng: 127.047377408384,
    available_time_start_hour: 13,
    available_time_start_minute: 0,
    available_time_end_hour: 15,
    available_time_end_minute: 0,
    chat_tags: ["다음에도 상담받고 싶은", "친절한", "꼼꼼한"],
    info_tags: ["영유아어린이영양제", "근처소아과", "주말오전영업"],
    meter: 123,
  },
  {
    id: 2,
    name: "차은우",
    pharmacy_name: "잘생김",
    address: "충청북도 청주시 상당구 중고개로",
    lat: 37.5173319258532,
    lng: 127.047377408384,
    available_time_start_hour: 11,
    available_time_start_minute: 0,
    available_time_end_hour: 18,
    available_time_end_minute: 0,
    chat_tags: ["다음에도 상담받고 싶은", "친절한", "꼼꼼한"],
    info_tags: ["영유아어린이영양제", "근처소아과", "주말오전영업"],
    meter: 12,
  },
  {
    id: 3,
    name: "김펭수",
    pharmacy_name: "귀여움",
    address: "서울특별시 강남구 선릉로",
    lat: 37.5173319258532,
    lng: 127.047377408384,
    available_time_start_hour: 10,
    available_time_start_minute: 0,
    available_time_end_hour: 19,
    available_time_end_minute: 30,
    chat_tags: ["다음에도 상담받고 싶은", "친절한", "꼼꼼한"],
    info_tags: ["영유아어린이영양제", "근처소아과", "주말오전영업"],
    meter: 3,
  },
];
